--Add initial role
SELECT 1;
/* INSERT INTO role (ROLE_NAME) VALUES ('ROLE_USER') ON CONFLICT (ROLE_NAME) DO NOTHING;
INSERT INTO role (ROLE_NAME) VALUES ('ROLE_ADMIN') ON CONFLICT (ROLE_NAME) DO NOTHING; */




