import { ReduxProvider } from "@/redux/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Router from "../shared/components/router/router";
import { ConfigProvider } from "antd";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Flicker",
  description: "Generated by Flicker Team",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body suppressHydrationWarning={true}>
        <ReduxProvider>
          <ConfigProvider
            theme={{
              token: {
                ...poppins.style,
                fontSize: 16,
              },
            }}
          >
            <Router>{children}</Router>
          </ConfigProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
